ADD: models.py user테이블 수정
wecode-bootcamp-korea/20-2nd-BankHouse-backend pull request #3
Opened 2021-05-26 09:44 UTC by Dae-Hwan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
models.py user테이블 수정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
user테이블에서 user_information속성 null 값 추가

## 기타 질문 및 특이 사항
db에 csv파일 넣는중에 models.py 수정사항을 발견했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-05-26 10:40 UTC, Dae-Hwan commented
DB작업시 필요 수정 소요가 발생되어서 추가 푸시를 하였습니다.

2021-05-26 13:27 UTC, Kang-kyunghun requested changes

2021-05-26 13:27 UTC, Kang-kyunghun commented on db_uploader.py
> +import os
업로더 파일 제거해 주세요.

2021-05-27 01:56 UTC, Dae-Hwan commented on db_uploader.py
> +import os
수정 완료했습니다

2021-05-27 03:30 UTC, Kang-kyunghun commented
LGTM~~~!!

2021-05-27 03:30 UTC, merged