Add: 일반 로그인/회원가입 기능구현
wecode-bootcamp-korea/20-2nd-BankHouse-backend pull request #4
Opened 2021-05-29 03:59 UTC by kyeongraekim

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인/회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Users App 일반 로그인/회원가입 기능 추가
- 유닛테스트 기능 추가 및 구동 성공

## 기타 질문 및 특이 사항
- 이메일, 비밀번호 validation 관련해서, validator.py 파일을 일부러 안만들었는데 만드는게 더 좋은 판단일까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-05-31 01:37 UTC, Kang-kyunghun requested changes

2021-05-31 01:37 UTC, Kang-kyunghun commented on users/views.py
> +            user_info    = UserInformation.objects.filter(nickname=nickname)
password의 default에 False을 준 이유가 있을까요? 만약에 조건문을 위한 것이라면, None이 적합하다고 생각합니다. 애초에 원하는 데이터 타입이 boolean이 아니기 때문입니다.

2021-05-31 01:37 UTC, Kang-kyunghun commented on users/views.py
> +            if not password_validation.match(password) and password != None:
여기서는 또 조건을 None으로 주었네요. 그리고 None은 주로 is None 또는 is not None으로 사용합니다.

2021-05-31 01:37 UTC, Kang-kyunghun commented on users/views.py
> +                )
user가 생성되지 않았는데, 유저 정보를 먼저 생성한다는 것이 말이 안 된다고 생각됩니다. 
따라서 foreign key도 user가 가지고 있는 것이 아니고 user 정보가 가지고 있어야 될 것 같습니다.

2021-05-31 02:29 UTC, kyeongraekim commented on users/views.py
> +            user_info    = UserInformation.objects.filter(nickname=nickname)
넵 다시보니 제가 None을 의도하였는데 코드 작업 중 잘못된 정보를 참고하여 False를 기입하게 되었습니다.
수정 반영하겠습니다.

2021-05-31 04:07 UTC, kyeongraekim commented on users/views.py
> +            if not password_validation.match(password) and password != None:
네 수정 반영하겠습니다.

2021-05-31 04:09 UTC, kyeongraekim commented on users/views.py
> +                )
맞습니다. 저도 작성중에 코드 논리구조상 이상함을 느껴서 models.py 를 수정할 지, 
아니면 위 내용대로 기능을 구현할지 고민을 했었습니다.
말씀하신대로 수정 반영하겠습니다.

2021-06-01 06:55 UTC, Kang-kyunghun requested changes

2021-06-01 06:55 UTC, Kang-kyunghun commented on users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
```suggestion
            if not password:
                hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
```

2021-06-01 06:55 UTC, Kang-kyunghun commented on users/views.py
> +                password      = hashed_password,
```suggestion
                password      = password if not password else hashed_password,
```

2021-06-01 06:55 UTC, Kang-kyunghun commented on users/views.py
> +            User.objects.create(
```suggestion
            user = User.objects.create(
```

2021-06-01 06:55 UTC, Kang-kyunghun commented on users/views.py
> +                user_id       = user_info.first().id,
```suggestion
                user       = user,
```

2021-06-01 06:55 UTC, Kang-kyunghun commented on users/views.py
> +            user_info     = User.objects.filter(email=email)
```suggestion
            data      = json.loads(request.body)
            email     = data.get("email")
            password  = data.get("password", None)
            nickname  = data.get("nickname")
            is_expert = data.get("is_expert", False)
            kakao_id  = data.get("kakao_id", None)
```
필수인 것들은 key error가 나도록 수정해 주세요.

2021-06-01 06:55 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=404)
적절한 메시지로 수정해 주세요

2021-06-01 12:51 UTC, kyeongraekim commented on users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
네 수정 반영하겠습니다.

2021-06-01 12:52 UTC, kyeongraekim commented on users/views.py
> +                password      = hashed_password,
네 수정 반영하겠습니다.

2021-06-01 12:52 UTC, kyeongraekim commented on users/views.py
> +            User.objects.create(
네 수정 반영하겠습니다.

2021-06-01 12:52 UTC, kyeongraekim commented on users/views.py
> +                user_id       = user_info.first().id,
네 수정 반영하겠습니다.

2021-06-01 12:52 UTC, kyeongraekim commented on users/views.py
> +            user_info     = User.objects.filter(email=email)
네 수정 반영하겠습니다.

2021-06-01 12:54 UTC, kyeongraekim commented on users/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=404)
네 수정 반영하겠습니다.

2021-06-02 07:55 UTC, Kang-kyunghun requested changes

2021-06-02 07:55 UTC, Kang-kyunghun commented on users/tests.py
> +        client      = Client()
setUp에서 client가 필요가 없겠죠? 삭제해 주세요.

2021-06-02 07:55 UTC, Kang-kyunghun commented on users/tests.py
> +
UserInformation data도 만들었으니 해당 데이터 지우는 코드도 추가해 주세요.

2021-06-02 07:55 UTC, Kang-kyunghun commented on users/tests.py
> +        self.assertEqual(response.status_code, 201)
상태 코드만 확인하지 않고, 응답으로 나가는 데이터로 같이 확인해 주세요.

2021-06-02 07:55 UTC, Kang-kyunghun commented on users/tests.py
> +        hashed_password  = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
이 부분도 굳이 필요해 보이지 않습니다.

2021-06-02 15:52 UTC, kyeongraekim commented on users/tests.py
> +        client      = Client()
네 수정 반영하겠습니다.

2021-06-02 15:53 UTC, kyeongraekim commented on users/tests.py
> +
네 수정 반영하겠습니다.

2021-06-02 15:54 UTC, kyeongraekim commented on users/tests.py
> +        self.assertEqual(response.status_code, 201)
네 수정 반영하겠습니다.

2021-06-02 15:55 UTC, kyeongraekim commented on users/tests.py
> +        hashed_password  = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
네 수정 반영하겠습니다.

2021-06-03 05:38 UTC, merged

2021-06-03 05:38 UTC, Kang-kyunghun commented
LGTM~~!!