ADD: 게시물 필터링 기능구현
wecode-bootcamp-korea/20-2nd-BankHouse-backend pull request #5
Opened 2021-05-30 07:04 UTC by Dae-Hwan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 게시물 필터링 기능구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
 - 게시물 필터링 기능구현
 - 유닛테스트 기능 구현 및 구동 성공

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-05-31 01:47 UTC, Kang-kyunghun requested changes

2021-05-31 01:47 UTC, Kang-kyunghun commented on posts/views.py
> +        page        = int(request.GET.get('page', 1))
페이지네이션을 위한 것 같은데, 이 때는 프론트한테 offset과 limit를 모두 받아야 합니다. offset(=page), limit(=Max)

2021-05-31 01:47 UTC, Kang-kyunghun commented on posts/views.py
> +            #posts = posts.sorted(posts, key=lambda post: posts.like_set.count(), reverse=True)
1. 불필요한 주석은 제거해 주세요.
2. 이미 order_by_data라는 dictionary을 잘 만들어 주셨습니다. 따라서 if절이 없이도 간단히 만들 수 있습니다. 한 번 생각해 보세요.

2021-05-31 01:47 UTC, Kang-kyunghun commented on posts/views.py
> +            ]
데이터 주는 부분은 같이 한 번 볼게요

2021-06-01 01:33 UTC, Dae-Hwan commented on posts/views.py
> +        page        = int(request.GET.get('page', 1))
넵 수정했습니다

2021-06-01 01:33 UTC, Dae-Hwan commented on posts/views.py
> +            #posts = posts.sorted(posts, key=lambda post: posts.like_set.count(), reverse=True)
넵 수정했습니다

2021-06-01 01:33 UTC, Dae-Hwan commented on posts/views.py
> +            ]
넵

2021-06-01 07:07 UTC, Kang-kyunghun commented
test code set up 부분 수정해 주세요.

2021-06-01 07:09 UTC, Kang-kyunghun requested changes

2021-06-01 07:09 UTC, Kang-kyunghun commented on db_uploader.py
> +import os
업로드 파일 제거하고 깃이그노에 추가해 주세요.

2021-06-01 07:09 UTC, Kang-kyunghun commented on posts/views.py
> +        limit       = int(request.GET.get('limit', None))
limit도 default 값 넣어 주세요.

2021-06-01 07:09 UTC, Kang-kyunghun commented on posts/tests.py
> +        #livingtype
어떤 데이터가 들어가는지 명확하게 나타나도록 수정해 주세요.

2021-06-02 06:44 UTC, Dae-Hwan commented on posts/views.py
> +        limit       = int(request.GET.get('limit', None))
넵 수정했습니다

2021-06-02 06:44 UTC, Dae-Hwan commented on posts/tests.py
> +        #livingtype
넵 수정했습니다

2021-06-02 06:50 UTC, Dae-Hwan commented on db_uploader.py
> +import os
넵 수정했습니다

2021-06-03 01:33 UTC, Kang-kyunghun requested changes

2021-06-03 01:33 UTC, Kang-kyunghun commented on posts/tests.py
> +
제거해 주세요.

2021-06-03 07:42 UTC, Kang-kyunghun commented
고생 많았습니다~

2021-06-03 07:42 UTC, merged