Add: 소셜 로그인 기능 구현
wecode-bootcamp-korea/20-2nd-BankHouse-backend pull request #6
Opened 2021-05-30 09:10 UTC by kyeongraekim

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-  소셜 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-  유저 이메일을 중심으로한 소셜 로그인 기능 구현
- MockResponse를 이용한 유닛테스트 성공

## 기타 질문 및 특이 사항
- 로그인은 일반로그인과 소셜로그인을 구분지었지만, 회원가입은 일반 로그인에 통합시켰습니다. 소셜 회원가입도 따로 분리시키는게 나을지 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

<img width="1440" alt="Screen Shot 2021-05-28 at 2 45 11 PM" src="https://user-images.githubusercontent.com/73090474/120098669-384dfe00-c172-11eb-870d-a0d8bfbbb84d.png">

2021-05-31 01:42 UTC, Kang-kyunghun requested changes

2021-05-31 01:42 UTC, Kang-kyunghun commented on users/views.py
> +            email                 = kakao_account.get("email")
가장 긴 변수를 기준으로 정렬하면 좋을 것 같아요
```suggestion
            access_token      = request.headers.get('Authorization', None)
            headers           = {"Authorization" : f"Bearer {access_token}"}
            kakao_login_data  = requests.get("https://kapi.kakao.com/v2/user/me", headers=headers).json()
            kakao_account     = kakao_login_data["kakao_account"]
            email             = kakao_account.get("email")  
```

2021-05-31 01:42 UTC, Kang-kyunghun commented on users/views.py
> +            if kakao_login_data.get('code') == -401:
코드가 -401이 있나요?(궁금)

2021-05-31 01:42 UTC, Kang-kyunghun commented on users/views.py
> +
소셜로그인으로 로그인 하는데, 그 조건이 이미 소셜 로그인으로 로그인 할 이메일이 가입되어 있어야 되는 조건으로 기획 한건가요?

2021-05-31 06:34 UTC, kyeongraekim commented on users/views.py
> +            if kakao_login_data.get('code') == -401:
네 카카오 디벨로퍼스 사이트를 확인해보니 아래의 상황에서 사용하는 것이라고 설명이 되어있습니다.

"유효하지 않은 앱키나 액세스 토큰으로 요청한 경우
토큰 값이 잘못되었거나 만료되어 유효하지 않은 경우로 토큰 갱신 필요"

2021-05-31 16:05 UTC, kyeongraekim commented on users/views.py
> +            email                 = kakao_account.get("email")
네 수정 반영하겠습니다.

2021-05-31 17:05 UTC, kyeongraekim commented on users/views.py
> +
네 맞습니다. 저희 조 기획상 일반/소셜 회원가입 시에 유저의 관련 정보가 모두 은행의 집 db에 들어오도록 되어있습니다.
따라서 카카오로 로그인을 하여도 저희 db에 해당 유저의 이메일이 기존재할 것이라 판단하여 작성한 코드입니다.

위 방법 말고도, 카카오 로그인 뷰에서 해당 유저가 없으면 가입을 바로 하게끔 하는 방법이 차선책으로 준비가 되어있어서,
현재 진행중인 방안이 여러 이유로 구현이 힘들게 된다면 get or create 나 if not ~~ exists()문을 써서 
카카오로그인 뷰에서 회원가입을 가능케 하겠습니다.

2021-06-01 06:57 UTC, Kang-kyunghun requested changes

2021-06-01 06:57 UTC, Kang-kyunghun commented on users/views.py
> +            email            = kakao_account.get("email", None)
꼭 필요한 값이므로 get 대신에 []으로 바꿔주세요.

2021-06-01 06:57 UTC, Kang-kyunghun commented on users/tests.py
> +        self.assertEqual(response.status_code, 200)
코드만 아니고 출력 결과도 포함시켜 주세요.

2021-06-01 13:27 UTC, Kang-kyunghun requested changes

2021-06-01 13:27 UTC, Kang-kyunghun commented on posts/views.py
> +
1. 공백 제거
2. 코드가 완성이 안 되어 있네요.

2021-06-01 13:28 UTC, Kang-kyunghun commented
소셜로그인 브렌치인데 코멘트 코드까지 같이 있습니다. 브렌치 나누어서 따로 push 해주세요.

2021-06-01 14:28 UTC, kyeongraekim commented on posts/views.py
> +
네 리베이스 도중 착오가 생겨서 잘못 올린 것 같습니다.
수종하여 재업로드하겠습니다

2021-06-02 12:50 UTC, closed without merging